In [34]:
import pandas as pd
import os


import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

In [46]:
import itertools

In [42]:
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM

from keras.callbacks import EarlyStopping

from sklearn.preprocessing import StandardScaler

In [3]:

# Previously sorted train.csv 
#     using df.sort_values(by=['crew', 'experiment', 'time'])
df = pd.read_csv('data/sorted_train.csv')

In [26]:
df.iloc[0]

crew                  1
experiment           CA
time          0.0117188
seat                  1
eeg_fp1        -5.28545
eeg_f7          26.7758
eeg_f8         -9.52731
eeg_t4         -12.7932
eeg_t6          16.7178
eeg_t5          33.7375
eeg_t3          23.7123
eeg_fp2        -6.69587
eeg_o1          29.2321
eeg_p3          24.8429
eeg_pz          3.92134
eeg_f3           18.447
eeg_fz          1.07547
eeg_f4          3.09029
eeg_c4           37.369
eeg_p4          17.4376
eeg_poz         19.2019
eeg_c3          20.5968
eeg_cz         -3.95115
eeg_o2          14.5076
ecg               -4520
r               817.706
gsr              388.83
event                 A
Name: 0, dtype: object

In [23]:
df.shape

(4867421, 28)

In [57]:
def what_records(dfx):
    return [(int(x), y) for (x,y) in json.loads(dfx['time'].to_json(orient='columns')).items()]

In [62]:
        df[['crew', 'seat', 'time', 'r', 'experiment', 'event']].iloc[6600:6615]


crew  seat        time           r experiment event
6600     1     1  109.988281  817.437988         CA     C
6601     1     0  109.988281  664.265991         CA     C
6602     1     0  109.992188  664.265991         CA     C
6603     1     1  109.992188  817.442017         CA     C
6604     1     1  109.996094  817.442017         CA     C
6605     1     0  109.996094  664.265991         CA     C
6606     1     0   11.000000  664.331970         CA     C
6607     1     1   11.000000  817.898987         CA     C
6608     1     0   11.003906  664.331970         CA     C
6609     1     1   11.003906  817.898987         CA     C
6610     1     0   11.007812  664.281982         CA     C
6611     1     1   11.007812  817.898987         CA     C
6612     1     0   11.011719  664.281982         CA     C
6613     1     1   11.011719  817.898987         CA     C
6614     1     0   11.015625  664.281982         CA     C

In [63]:
choices = ([1,2], [0,1], ['CA', 'DA', 'SS'])
for crew, seat, experiment in itertools.product(*choices):
    query = (df.crew == crew)&(df.seat == seat)& (df.experiment == experiment)
    print(df[query].shape)

(92131, 28)
(92077, 28)
(39563, 28)
(92168, 28)
(92130, 28)
(39583, 28)
(92133, 28)
(92194, 28)
(92131, 28)
(92099, 28)
(92099, 28)
(92212, 28)


In [156]:
reshape_y(encode_class(y_train), 4).shape

(4721, 4)

In [159]:
# initial toy model w/ just a handful of inputs.
model = bake_model(x_train, reshape_y(encode_class(y_train), 4),
                   x_test, reshape_y(encode_class(y_test), 4), epochs=2)
# y2 = reshape_y(y, 6)

Train...
Train on 4721 samples, validate on 243 samples
Epoch 1/2
 - 38s - loss: 0.9748 - acc: 0.7672 - val_loss: 0.2220 - val_acc: 1.0000
Epoch 2/2
 - 39s - loss: 0.6874 - acc: 0.7766 - val_loss: 0.1880 - val_acc: 1.0000


In [160]:
pred = model.predict(x_train[:5])
predict_classes = np.argmax(pred,axis=1)

In [165]:
pred, predict_classes, y_train[:5]

(array([[ 0.3049076 , -0.2723024 ,  0.67816526, -0.01257241],
        [ 0.3049076 , -0.2723024 ,  0.67816526, -0.01257241],
        [ 0.3049076 , -0.2723024 ,  0.67816526, -0.01257241],
        [ 0.3049076 , -0.2723024 ,  0.67816526, -0.01257241],
        [ 0.30490765, -0.27230242,  0.6781652 , -0.0125725 ]],
       dtype=float32),
 array([2, 2, 2, 2, 2]),
 array(['A', 'A', 'A', 'A', 'A'], dtype='<U1'))

In [136]:
trainseqs.shape, yarray.shape
print(trainseqs.shape)
# print(np.resize(trainseqs, (221, 256, 1)).shape) 
print(trainseqs[0][:5])
print(yarray.shape)

print(Counter(encode_class(yarray)))
# print (type(yarray))

(221, 256, 1)
[[665.0020139999998]
 [665.0020139999998]
 [665.0020139999998]
 [665.0020139999998]
 [665.0020139999998]]
(221,)
Counter({0: 221})


In [167]:
df.r.describe()

count    4.867421e+06
mean     7.376090e+02
std      8.187979e+01
min      4.820600e+02
25%      6.631430e+02
50%      7.434380e+02
75%      8.134120e+02
max      8.401840e+02
Name: r, dtype: float64

In [240]:
# First model train, 
%time out, model = runner()

Start make_data 2019-05-16 13:41:08
Start building training set 2019-05-16 13:41:08
Start building testing set 2019-05-16 13:41:09
Start bake_model 2019-05-16 13:41:10
Train... 2019-05-16 13:41:11
Train on 91874 samples, validate on 91876 samples
Epoch 1/2
 - 874s - loss: 0.1881 - acc: 0.1129 - val_loss: 1.0480e-07 - val_acc: 0.2500
Epoch 2/2
 - 893s - loss: 0.1271 - acc: 0.0466 - val_loss: 1.0480e-07 - val_acc: 0.0000e+00
CPU times: user 1h 18min 13s, sys: 32min 39s, total: 1h 50min 53s
Wall time: 29min 30s


In [247]:
# (Running make_data() one more time to get additional intermediate data) 
outdata = make_data(df, crews={'training': [1],
                        'test': [2]},
              sequence_window=256, row_cap_per_person=None,
             feature_cols={'r': simple_scaler})

Start building training set 2019-05-16 14:57:24
Start building testing set 2019-05-16 14:57:25


In [253]:
# Review that model...
print(model, out['x_test'].shape, out['y_test'].shape)
pred = model.predict(out['x_test'])
predict_classes = np.argmax(pred, axis=1)
print('pred[:5]', pred[:5])
print('predict classes[:5]', predict_classes[:5])
print('y test', out['y_test'][:5])
print('y test original', outdata['y_test_original'][:5])
# print('Counter y test original', --)
# print('Counter predict classes', --)

<keras.engine.sequential.Sequential object at 0x15133e2b0> (91876, 256, 1) (91876, 4)
pred[:5] [[-1.1603819  -0.6849162   4.523494   -0.68110585]
 [-1.1603718  -0.684935    4.523487   -0.6811167 ]
 [-1.1603596  -0.6849571   4.523492   -0.6811271 ]
 [-1.1603528  -0.6849684   4.523488   -0.68113387]
 [-1.1603469  -0.68497616  4.523484   -0.68113863]]
predict classes[:5] [2 2 2 2 2]
y test [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]
y test original ['C' 'C' 'C' 'C' 'C']
Counter y test original Counter({'C': 91876})
Counter predict classes Counter({'C': 91876})


In [257]:
# - ok darn looks like the input data looks corrupt since theres just one class represented
print('Counter y test original', Counter(outdata['y_test_original']))
print('Counter predict classes', Counter(predict_classes))
print(len(Counter(outdata['y_test_original'])))
print (outdata['y_test'].shape)

Counter y test original Counter({'C': 91876})
Counter predict classes Counter({2: 91876})
1
(91876, 4)


In [261]:
# ...
outdata = make_data(df, crews={'training': [1],
                        'test': [2]},
              sequence_window=256, row_cap_per_person=None,
             feature_cols={'r': simple_scaler})

Start building training set 2019-05-16 15:28:22
Start building testing set 2019-05-16 15:28:23


In [267]:
print(outdata['traindf'].shape)
print(outdata['traindf'].event.value_counts())

447652/256

(447652, 7)
A    235891
C    180853
D     23219
B      7689
Name: event, dtype: int64


1748.640625

In [ ]:
# There are not enough sequences. Only ~91876 , 
# - but should be  around  447652 - 256 . 


In [260]:
# Okay so since there are 9 crews in this data , and indeed I assume the test data 
#     crews are the same people. Anyway, not too important for now.
#     But I can split the data into 6 for train and 3 for testing.
#
# - So as a preliminary simple model, I want to just use the `r` , the respiration data.
# - And I suppose it doesn't really matter all too much if both crew member data
#      are intermingled, but I think I will split that away for now.

encode_class = np.vectorize(lambda x: {'A': 0,
                                      'B': 1,
                                      'C': 2,
                                      'D': 3}.get(x))

simple_scaler = lambda x, a: x*a 

def timestamp():
    return datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

def do_standard_scaling(df, cols, scalar_dict=None):
    if scalar_dict is None:    
        scalar_dict = {col: StandardScaler().fit(df[[col]]) for col in cols}
        
    for col in cols:
        df[col + '_scaled'] = np.resize(
            scalar_dict[col].transform(df[[col]]),
            (df.shape[0],))
    
    return scalar_dict, df


def make_data(df, crews={'training': [1],
                        'test': [2]},
              sequence_window=256, row_cap_per_person=None,
             feature_cols={'r': 'standard_scaler'}):

    # current sorted as ['crew', 'experiment', 'time']
    [0, 1] # each seat
    ['CA', 'DA', 'SS'] # experiment
    
    sort_cols = ['crew', 'seat', 'experiment', 'time']
    target_col = 'event'
    
    what_cols = sort_cols + list(feature_cols) + [target_col]

    # Training
    traindf = df[df.crew.isin(crews['training'])][what_cols].sort_values(
        by=sort_cols).copy()
    
    scalar_dict, _ = do_standard_scaling(traindf, ['r'])
    
    print('Start building training set', timestamp())
    x_train, y_train = get_windows(traindf, ['r_scaled', 'event'],
                                   sequence_window)
    
    # Testing
    testdf = df[df.crew.isin(crews['test'])][what_cols].sort_values(
        by=sort_cols).copy()

    _, _ = do_standard_scaling(testdf, ['r'], scalar_dict)
    
    
    print('Start building testing set', timestamp())
    x_test, y_test = get_windows(testdf, ['r_scaled', 'event'],
                                 sequence_window)


    return {
        "x_train": x_train,
        "y_train": reshape_y(encode_class(y_train), 4), # y_train,
        "x_test": x_test,
        "y_test": reshape_y(encode_class(y_test), 4), # y_test
        "y_train_original": y_train,
        "y_test_original": y_test,
        "traindf": traindf,
        "testdf": testdf,
    }


def runner():
    print('Start make_data', timestamp())
    outdata = make_data(df, crews={'training': [1],
                        'test': [2]},
              sequence_window=256, row_cap_per_person=None,
             feature_cols={'r': simple_scaler})
    
    validate_data(outdata)

    print('Start bake_model', timestamp())
    model = bake_model(**outdata, epochs=2)
    return outdata, model

def validate_data(data):
    assert len(Counter(data['y_train_original'])) > 1
    assert len(Counter(data['y_test_original'])) > 1
  
    
def get_windows(df, cols, window_size):
    #
    windows = []
    Y = []
    choices = (df.crew.unique().tolist(), [0, 1], ['CA', 'DA', 'SS'])
    for crew, seat, experiment in itertools.product(*choices):
        query = (df.crew == crew)&(df.seat == seat)&(df.experiment == experiment)
        thisdf = df[query][cols]
        return to_sequences(thisdf.values, window_size) 
        # y = thisdf.iloc[-1].event

# Borrowing parts of this func from 
# https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class10_lstm.ipynb
def to_sequences(obs, seq_size, incols=[0], outcols=[1]):
    x = []
    y = []

    for i in range(len(obs)-seq_size-1):
        #print(i)
        window = obs[i:(i+seq_size)][..., 0]
        after_window = obs[i+seq_size, 1] # FIXME :off by 1 error here?
        # window = [[x] for x in window]

        x.append(window)
        y.append(after_window)
        
    xarr = np.array(x)
    yarr = np.array(y)
    return (np.resize(xarr, xarr.shape + (1,)),
            yarr)

def bake_model(x_train, y_train, x_test, y_test, epochs=1):
    
    model = Sequential()
    model.add(LSTM(64, dropout=0.2, recurrent_dropout=0.2,
                   input_shape=(None, 1)))
    # model.add(Dense(32))

    # 4 because 'A', 'B', 'C', 'D'.
    model.add(Dense(4))

    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])

    # initial_state ... for the LSTM , hmm


    monitor = EarlyStopping(monitor='val_loss',
                            min_delta=1e-3, patience=5, verbose=1, mode='auto')
    print('Train...', timestamp())

    # https://www.tensorflow.org/api_docs/python/tf/keras/models/Model#arguments_8
    # - hmm so fit() can take a generator sometimes.
    # - use_multiprocessing=True 
    model.fit(x_train, y_train, validation_data=(x_test, y_test),
              callbacks=[monitor], verbose=2, epochs=epochs)

    return model

def reshape_y(y, num_cols):

    # y = np.array([1,2,3,2,3,1],dtype=np.int32)

    # Convert y2 to dummy variables
    y2 = np.zeros((y.shape[0], num_cols), dtype=np.float32)
    y2[np.arange(y.shape[0]), y] = 1.0
    return y2
