In [1]:
# boiler plate
from collections import Counter
import pickle
from importlib import reload
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler


import ipdb
import mytf.utils as mu

tf.enable_eager_execution()

print(tf.executing_eagerly())

True


In [2]:
with open('models/2019-07-21T1815-UTC-outdata-SUBSET50k.pkl', 'rb') as fd:
    julydata = pickle.load(fd)

In [3]:
class_weights = {0: 1.0, 1: 1.3, 2: 1.0, 3: 1.0}
training_indices = np.arange(0, julydata['x_train'].shape[0], 1)
print('training indices...', training_indices.shape)

dataset_batches = mu.build_dataset_weighty_v3(
    julydata,
    training_indices, 
    class_weights,
    batch_size=1000)

training indices... (50000,)
Start build v3: .. doesnt add up to 1.0
num slices 50
size_remainder,  0
Counter({0: 504, 2: 426, 3: 49, 1: 21})
weights_per_class,  tf.Tensor([0.00198413 0.06190476 0.00234742 0.02040816], shape=(4,), dtype=float32)
1006.2999999999997
Counter({0: 552, 2: 385, 3: 48, 1: 15})
weights_per_class,  tf.Tensor([0.00181159 0.08666667 0.0025974  0.02083333], shape=(4,), dtype=float32)
1004.4999999999995
Counter({0: 499, 2: 430, 3: 51, 1: 20})
weights_per_class,  tf.Tensor([0.00200401 0.065      0.00232558 0.01960784], shape=(4,), dtype=float32)
1005.9999999999995
Counter({0: 537, 2: 393, 3: 46, 1: 24})
weights_per_class,  tf.Tensor([0.0018622  0.05416666 0.00254453 0.02173913], shape=(4,), dtype=float32)
1007.1999999999996
Counter({0: 532, 2: 386, 3: 62, 1: 20})
weights_per_class,  tf.Tensor([0.0018797  0.065      0.00259067 0.01612903], shape=(4,), dtype=float32)
1005.9999999999995
Counter({0: 508, 2: 427, 3: 50, 1: 15})
weights_per_class,  tf.Tensor([0.0019685  0

In [4]:
with tf.Session() as sess:

    # okay... now try use that ..
    model = tf.keras.Sequential([
        tf.keras.layers.LSTM(64,   dropout=0.2, recurrent_dropout=0.2,
                    batch_input_shape=(None, 256, 3), 
                  ),
        # 4 because 'A', 'B', 'C', 'D'.
        tf.keras.layers.Dense(4)
    ])

    %time loss_history = mu.do_train(model, dataset_batches)

    

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


RuntimeError: dataset.__iter__() is only supported when eager execution is enabled.

In [ ]:
# umm what this time i did enable eager execution. ok so probably using tf.Session() 
# means i am perhaps selectively saying do not use eager? 

In [5]:
sess = tf.Session()

In [6]:
sess.run(tf.global_variables_initializer())

TypeError: Fetch argument None has invalid type <class 'NoneType'>